const DATE_FORMAT_YEAR_FIRST_WITH_HYPHEN = 'YYYY-MM-DD';
const DATE_FORMAT_VI = 'DD/MM/YYYY';
const DEFAULT_DATE_TIME_FORMAT = 'DD/MM/YYYY HH:mm:ss';

export {
  DATE_FORMAT_VI,
  DATE_FORMAT_YEAR_FIRST_WITH_HYPHEN,
  DEFAULT_DATE_TIME_FORMAT,
};
